/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context as ctx } from "./../src/context"
import { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>
    crud: any
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AreaReservationSlotOrderByInput: { // input type
    startTime?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ReservationSlotAreaIdStartTimeCompoundUniqueInput: { // input type
    areaId: string; // String!
    startTime: NexusGenScalars['DateTime']; // DateTime!
  }
  ReservationSlotWhereUniqueInput: { // input type
    areaId_startTime?: NexusGenInputs['ReservationSlotAreaIdStartTimeCompoundUniqueInput'] | null; // ReservationSlotAreaIdStartTimeCompoundUniqueInput
    id?: string | null; // String
  }
  TableAreaIdDisplayNameCompoundUniqueInput: { // input type
    areaId: string; // String!
    displayName: string; // String!
  }
  TableWhereUniqueInput: { // input type
    areaId_displayName?: NexusGenInputs['TableAreaIdDisplayNameCompoundUniqueInput'] | null; // TableAreaIdDisplayNameCompoundUniqueInput
    id?: string | null; // String
  }
}

export interface NexusGenEnums {
  ReservationStatus: "CheckedIn" | "Cleared" | "Pending" | "Reserved"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
  JSONObject: any
}

export interface NexusGenObjects {
  Area: { // root type
    displayName: string; // String!
  }
  Band: { // root type
    endTime: NexusGenScalars['DateTime']; // DateTime!
    genre?: string | null; // String
    id: number; // Int!
    name: string; // String!
    startTime: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: {};
  Query: {};
  Reservation: { // root type
    id: number; // Int!
    status: NexusGenEnums['ReservationStatus']; // ReservationStatus!
  }
  ReservationSlot: { // root type
    endTime: NexusGenScalars['DateTime']; // DateTime!
    startTime: NexusGenScalars['DateTime']; // DateTime!
  }
  SlotAvailability: { // root type
    availabilityForLargerPartySize?: number | null; // Int
    availabilityForSmallerPartySize?: number | null; // Int
    available: boolean; // Boolean!
  }
  Table: { // root type
    displayName: string; // String!
    id: string; // String!
    maxCapacity: number; // Int!
  }
  Viewer: { // root type
    displayName: string; // String!
    email: string; // String!
    profilePicture?: string | null; // String
  }
}

export interface NexusGenInterfaces {
  Node: NexusGenRootTypes['Area'] | NexusGenRootTypes['ReservationSlot'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Area: { // field return type
    displayName: string; // String!
    id: string; // ID!
    reservationSlot: NexusGenRootTypes['ReservationSlot'][]; // [ReservationSlot!]!
    table: NexusGenRootTypes['Table'][]; // [Table!]!
  }
  Band: { // field return type
    endTime: NexusGenScalars['DateTime']; // DateTime!
    genre: string | null; // String
    id: number; // Int!
    name: string; // String!
    startTime: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: { // field return type
    cancelReservation: boolean | null; // Boolean
    confirmReservation: NexusGenRootTypes['Reservation'] | null; // Reservation
    requestReservation: NexusGenRootTypes['Reservation'] | null; // Reservation
    updateReservation: NexusGenRootTypes['Reservation'] | null; // Reservation
  }
  Query: { // field return type
    areas: NexusGenRootTypes['Area'][]; // [Area!]!
    node: NexusGenRootTypes['Node'] | null; // Node
    reservationsForToken: NexusGenRootTypes['Reservation'][]; // [Reservation!]!
    viewer: NexusGenRootTypes['Viewer'] | null; // Viewer
  }
  Reservation: { // field return type
    id: number; // Int!
    reservationSlots: NexusGenRootTypes['ReservationSlot'][]; // [ReservationSlot!]!
    status: NexusGenEnums['ReservationStatus']; // ReservationStatus!
  }
  ReservationSlot: { // field return type
    area: NexusGenRootTypes['Area']; // Area!
    bandsPlaying: NexusGenRootTypes['Band'][]; // [Band!]!
    endTime: NexusGenScalars['DateTime']; // DateTime!
    id: string; // ID!
    slotAvailability: NexusGenRootTypes['SlotAvailability']; // SlotAvailability!
    startTime: NexusGenScalars['DateTime']; // DateTime!
  }
  SlotAvailability: { // field return type
    availabilityForLargerPartySize: number | null; // Int
    availabilityForSmallerPartySize: number | null; // Int
    available: boolean; // Boolean!
  }
  Table: { // field return type
    area: NexusGenRootTypes['Area']; // Area!
    displayName: string; // String!
    id: string; // String!
    maxCapacity: number; // Int!
  }
  Viewer: { // field return type
    displayName: string; // String!
    email: string; // String!
    profilePicture: string | null; // String
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  Area: { // field return type name
    displayName: 'String'
    id: 'ID'
    reservationSlot: 'ReservationSlot'
    table: 'Table'
  }
  Band: { // field return type name
    endTime: 'DateTime'
    genre: 'String'
    id: 'Int'
    name: 'String'
    startTime: 'DateTime'
  }
  Mutation: { // field return type name
    cancelReservation: 'Boolean'
    confirmReservation: 'Reservation'
    requestReservation: 'Reservation'
    updateReservation: 'Reservation'
  }
  Query: { // field return type name
    areas: 'Area'
    node: 'Node'
    reservationsForToken: 'Reservation'
    viewer: 'Viewer'
  }
  Reservation: { // field return type name
    id: 'Int'
    reservationSlots: 'ReservationSlot'
    status: 'ReservationStatus'
  }
  ReservationSlot: { // field return type name
    area: 'Area'
    bandsPlaying: 'Band'
    endTime: 'DateTime'
    id: 'ID'
    slotAvailability: 'SlotAvailability'
    startTime: 'DateTime'
  }
  SlotAvailability: { // field return type name
    availabilityForLargerPartySize: 'Int'
    availabilityForSmallerPartySize: 'Int'
    available: 'Boolean'
  }
  Table: { // field return type name
    area: 'Area'
    displayName: 'String'
    id: 'String'
    maxCapacity: 'Int'
  }
  Viewer: { // field return type name
    displayName: 'String'
    email: 'String'
    profilePicture: 'String'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  Area: {
    reservationSlot: { // args
      after?: NexusGenInputs['ReservationSlotWhereUniqueInput'] | null; // ReservationSlotWhereUniqueInput
      before?: NexusGenInputs['ReservationSlotWhereUniqueInput'] | null; // ReservationSlotWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['AreaReservationSlotOrderByInput'][] | null; // [AreaReservationSlotOrderByInput!]
    }
    table: { // args
      after?: NexusGenInputs['TableWhereUniqueInput'] | null; // TableWhereUniqueInput
      before?: NexusGenInputs['TableWhereUniqueInput'] | null; // TableWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    cancelReservation: { // args
      token: string; // String!
    }
    confirmReservation: { // args
      token: string; // String!
    }
    requestReservation: { // args
      otherEmails: string[]; // [String!]!
      otherPersons: string[]; // [String!]!
      primaryEmail: string; // String!
      primaryPerson: string; // String!
      slotIds: string[]; // [ID!]!
    }
    updateReservation: { // args
      otherEmails: string[]; // [String!]!
      otherPersons: string[]; // [String!]!
      primaryEmail: string; // String!
      primaryPerson: string; // String!
      token: string; // String!
    }
  }
  Query: {
    node: { // args
      id: string; // ID!
    }
    reservationsForToken: { // args
      token: string; // String!
    }
  }
  Reservation: {
    reservationSlots: { // args
      after?: NexusGenInputs['ReservationSlotWhereUniqueInput'] | null; // ReservationSlotWhereUniqueInput
      before?: NexusGenInputs['ReservationSlotWhereUniqueInput'] | null; // ReservationSlotWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  ReservationSlot: {
    slotAvailability: { // args
      partySize: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Node: "Area" | "ReservationSlot"
}

export interface NexusGenTypeInterfaces {
  Area: "Node"
  ReservationSlot: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "Node";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ctx;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}