name: Deploy

on:
  push:
    branches:
      - gcp

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: oven-sh/setup-bun@v2
      - name: Prepare environment
        env:
          Dotenv: ${{ secrets.DOTENV_ME }}
        run: |
          echo "DOTENV_ME=$Dotenv" > .env.me
          bun install
          bun dotenv-vault pull
          bun dotenv-vault pull production
          bun scripts/merge-envs.ts

      - name: 'Typecheck'
        run: |
          bun generate:prisma
          bun tsc --noEmit

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'

      - name: 'Build Docker image'
        run: gcloud builds submit --config cloudbuild.yaml .

      - name: 'Deploy container'
        run: gcloud run deploy api --image europe-west1-docker.pkg.dev/gmail-reminder-api/cloud-run-source-deploy/api:latest --env-vars-file ./.env.json --region europe-west1 --allow-unauthenticated
