name: Deploy

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Install dependencies
        run: yarn
      - name: Typecheck and build
        run: |
          yarn generate:prisma
          yarn build
      - name: Create ENV
        env:
          Dotenv: ${{ secrets.DOTENV_ME }}
        run: |
          echo "DOTENV_ME=$Dotenv" > .env.me
          yarn dotenv-vault pull
          yarn dotenv-vault pull production
          yarn ts-node scripts/merge-envs.ts
          rm -rf .env.me
      - name: Create Sentry release
        env:
          Release: api@${{ github.run_number }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          printf "\nRELEASE=$Release" >> .env
          yarn sentry-cli releases new $Release
          yarn sentry-cli releases files $Release upload-sourcemaps upload-sourcemaps dist
          yarn sentry-cli releases finalize $Release
      - name: Deploy
        env:
          Host: kultursp@kulturspektakel.de
          Dir: /var/www/virtual/kultursp/api.kulturspektakel.de
        run: |
          rsync -avz --delete --exclude node_modules --exclude src . $Host:$Dir
          ssh $Host "cd $Dir && ./scripts/deploy.sh"
